version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    working_directory: ~/sampleApp
    steps:
      - checkout
      - restore_cache:
        keys:
          - app-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          - app-
      - run: bundle install --path vendor/bundle
      - run: yarn install
      - save_cache:
        key: app-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
        paths:
          - vendor/bundle
          - node_modules
      - run: cp config/database.yml.circleci config/database.yml
      - run: bundle exec rake db:create db:schema:load
      - run: bundle exec bin/webpack
      - run: bundle exec rspec
      - run:
          name: Run test
          command: "ruby test/models/guest_test.rb"

workflows:
  version: 2.1
  workflows:
    jobs:
      - test
